no_trace: false
debounce: 300
ignore: \.git/
trig_async: [sfu, p2p]

rules:
  - name: sfu
    match: \.(go|yaml)$
    ignore: _test\.go$
    command: go run sfu/*.go

  - name: p2p
    match: \.(go|yaml)$
    ignore: _test\.go$
    command: go run p2p/*.go

