no_trace: false
debounce: 300
ignore: \.git/
trig_async: [sfu, p2p]

rules:
  - name: sfu
    match: sfu/.*\.(go|yaml|html|env|js)$
    ignore: _test\.go$
    command: go run sfu/*.go

  - name: p2p
    match: p2p/.*\.(go|yaml|html|env|js)$
    ignore: _test\.go$
    command: go run p2p/*.go

